[project]
name = "krippendorff-aleph-alpha"
version = "0.1.17"
authors = [{ name = "Zahra Kolagar", email = "zahra.kolagar@aleph-alpha.com" }]
description = "A robust implementation of Krippendorff's Alpha"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
    "types-pyyaml>=6.0.12.20250516",
]

[dependency-groups]
dev = [
    "bandit==1.8.3",
    "build==1.2.2.post1",
    "gitpython==3.1.44",
    "mypy==1.16.0",
    "pylint==3.3.7",
    "pytest==8.3.5",
    "pytest-benchmark==5.1.0",
    "pytest-cov==6.1.1",
    "pytest-mock==3.14.1",
    "pytest-xdist==3.7.0",
    "ruff==0.11.11",
    "toml==0.10.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/krippendorff_alpha"]

[tool.hatch.build.targets.sdist]
include = [
    "src/krippendorff_alpha",
]

[project.scripts]
lint = "infrastructure.task:run_ruff"
format = "infrastructure.task:run_format"
test = "infrastructure.task:run_pytest"
typecheck = "infrastructure.task:run_mypy"
all = "infrastructure.task:run_all"

[tool.mypy]
files = "src,tests"
strict = true
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests", ".venv"]

[tool.pytest.ini_options]
testpaths = ["tests"]
