[project]
name = "krippendorff-aleph-alpha"
authors = [{ name = "Zahra Kolagar", email = "zahra.kolagar@aleph-alpha.com" }]
description = "A robust implementation of Krippendorffâ€™s Alpha"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
