[project]
name = "krippendorff-aleph-alpha"
version = "0.1.0"
authors = [{ name = "Zahra Kolagar", email = "zahra.kolagar@aleph-alpha.com" }]
description = "A robust implementation of Krippendorffâ€™s Alpha"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "numpy==2.2.3",
    "pandas==2.2.3",
    "pydantic==2.10.6",
    "types-pyyaml==6.0.12.20241230",
]

[dependency-groups]
dev = [
    "bandit>=1.8.2",
    "gitpython>=3.1.44",
    "mypy>=1.14.1",
    "pylint>=3.3.4",
    "pytest>=8.3.4",
    "pytest-benchmark>=5.1.0",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-xdist>=3.6.1",
    "ruff>=0.9.4",
    "toml>=0.10.2",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
lint = "krippendorff_alpha.task:run_ruff"
format = "krippendorff_alpha.task:run_format"
test = "krippendorff_alpha.task:run_pytest"
typecheck = "krippendorff_alpha.task:run_mypy"
all = "krippendorff_alpha.task:run_all"

[tool.mypy]
files = "src,tests"
strict = true
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests", ".venv"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools]
packages = ["krippendorff_alpha"]
package-dir = { "" = "src" }
